create database tienda;

use tienda;

CREATE TABLE PRODUCTO 
(
	CODIGO INTEGER(10),
	NOMBRE VARCHAR(100),
	PRECIO DECIMAL(5,2),
	CODIGO_FABRICANTE INTEGER(10),
	
	CONSTRAINT PK_PRODUCTO PRIMARY KEY (CODIGO)
);

CREATE TABLE FABRICANTE
(
	CODIGO INTEGER(10),
	NOMBRE VARCHAR(100),
	
	CONSTRAINT PK_FABRICANTE PRIMARY KEY (CODIGO)
);

ALTER TABLE PRODUCTO ADD CONSTRAINT FK_CODIGO_FABRICANTE FOREIGN KEY (CODIGO_FABRICANTE) REFERENCES FABRICANTE(CODIGO);

INSERT INTO FABRICANTE VALUES (1, 'Asus');
INSERT INTO FABRICANTE VALUES (2, 'Lenovo');
INSERT INTO FABRICANTE VALUES (3, 'Hewlett-Packard');
INSERT INTO FABRICANTE VALUES (4, 'Samsung');
INSERT INTO FABRICANTE VALUES (5, 'Seagate');
INSERT INTO FABRICANTE VALUES (6, 'Crucial');
INSERT INTO FABRICANTE VALUES (7, 'Gigabyte');
INSERT INTO FABRICANTE VALUES (8, 'Huawei');
INSERT INTO FABRICANTE VALUES (9, 'Xiaomi');

INSERT INTO PRODUCTO VALUES (1, 'Disco duro SATA3 1TB', 86.99, 5);
INSERT INTO PRODUCTO VALUES (2, 'Memoria RAM DDR4 8GB', 120, 6);
INSERT INTO PRODUCTO VALUES (3, 'Disco SSD 1 TB', 150.99, 4);
INSERT INTO PRODUCTO VALUES (4, 'GeForce GTX 1050Ti', 185, 7);
INSERT INTO PRODUCTO VALUES (5, 'GeForce GTX 1080 Xtreme', 755, 6);
INSERT INTO PRODUCTO VALUES (6, 'Monitor 24 LED Full HD', 202, 1);
INSERT INTO PRODUCTO VALUES (7, 'Monitor 27 LED Full HD', 245.99, 1);
INSERT INTO PRODUCTO VALUES (8, 'Portátil Yoga 520', 559, 2);
INSERT INTO PRODUCTO VALUES (9, 'Portátil Ideapd 320', 444, 2);
INSERT INTO PRODUCTO VALUES (10, 'Impresora HP Deskjet 3720', 59.99, 3);
INSERT INTO PRODUCTO VALUES (11, 'Impresora HP Laserjet Pro M26nw', 180, 3);

INSERT INTO FABRICANTE (CODIGO, NOMBRE) VALUES (55,'BQ');

#ALTER TABLE FABRICANTE MODIFY CODIGO INTEGER(10) AUTO_INCREMENT;
#INSERT INTO FABRICANTE (NOMBRE) VALUES ('GOOGLE');

INSERT INTO PRODUCTO (CODIGO, NOMBRE, PRECIO, CODIGO_FABRICANTE) VALUES (34, 'Raton Hp ultra 4500', 60.50, 55);

#ejer4

SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM FABRICANTE WHERE NOMBRE='Asus';

DELETE FROM FABRICANTE WHERE NOMBRE='Xiaomi';

UPDATE FABRICANTE SET CODIGO = 20 WHERE NOMBRE = 'Lenovo';

UPDATE FABRICANTE SET CODIGO = 30 WHERE NOMBRE = 'Huawei';

UPDATE PRODUCTO SET PRECIO = PRECIO + 5;

DELETE FROM PRODUCTO WHERE NOMBRE LIKE '%Impresora%' AND PRECIO<200;

SET FOREIGN_KEY_CHECKS = 1; #activar FK





