--alter session set "_oracle_script"=true;  
--create user subidaNotaMoralesRafa identified by subidaNotaMoralesRafa;
--GRANT CONNECT, RESOURCE, DBA TO subidaNotaMoralesRafa;

CREATE TABLE FAMILIA 
(
	NOMBRE VARCHAR2(20),
	CARACTERISTICAS VARCHAR2(50),
	
	CONSTRAINT PK_FAMILIA PRIMARY KEY (NOMBRE)
);

CREATE TABLE GENERO 
(
	NOMBRE VARCHAR2(20),
	CARACTERISTICAS VARCHAR2(50),
	NOMBRE_FAMILIA VARCHAR(20),
	
	CONSTRAINT PK_GENERO PRIMARY KEY (NOMBRE),
	CONSTRAINT FK1_GENERO FOREIGN KEY (NOMBRE_FAMILIA) REFERENCES FAMILIA(NOMBRE)
);

CREATE TABLE ESPECIE
(
	NOMBRE VARCHAR2(20),
	CARACTERISTICAS VARCHAR2(50),
	NOMBRE_GENERO VARCHAR2(20),
	
	CONSTRAINT PK_ESPECIE PRIMARY KEY (NOMBRE),
	CONSTRAINT FK1_ESPECIE FOREIGN KEY (NOMBRE_GENERO) REFERENCES GENERO(NOMBRE)
);

CREATE TABLE PERSONA
(
	DNI VARCHAR2(9),
	NOMBRE VARCHAR2(20),
	DIRECCION VARCHAR2 (50),
	TELEFONO NUMBER(9),
	USUARIO VARCHAR2(10),
	
	CONSTRAINT PK_PERSONA PRIMARY KEY (DNI)
	
);

CREATE TABLE COLECCION
(
	PRECIO NUMBER(6,2),
	FECHA_INICIO DATE,
	N_EJEMPLARES NUMBER(5),
	DNI_COLECCION VARCHAR2(9),
	
	CONSTRAINT PK_COLECCION PRIMARY KEY (DNI_COLECCION),
	CONSTRAINT FK1_COLECCION FOREIGN KEY (DNI_COLECCION) REFERENCES PERSONA(DNI)
);

CREATE TABLE ZONA
(
	NOMBRE VARCHAR2(20),
	FECHA_CAPTURA DATE,
	HORA_CAPTURA VARCHAR2(5),
	NOMBRE_ESPECIE VARCHAR(20),
	DNI_COLECCION VARCHAR2(9),
	LOCALIDAD VARCHAR2(20),
	EXTENSION NUMBER(5),
	PROTEGIDA VARCHAR2(2),
	
	CONSTRAINT PK_ZONA PRIMARY KEY (NOMBRE)
);

CREATE TABLE EJEMPLAR_MARIPOSA
(
	FECHA_CAPTURA DATE,
	HORA_CAPTURA VARCHAR2(5),
	NOMBRE_ESPECIE VARCHAR(20),
	DNI_PERSONA VARCHAR2(9),
	NOMBRE_COMUN VARCHAR2(20),
	PRECIO_EJEMPLAR NUMBER(5,2),
	FECHA_COLECCION DATE,
	DNI_COLECCION VARCHAR2(9),
	NOMBRE_ZONA VARCHAR2(20),
	
	CONSTRAINT PK_EJEMPLAR_MARIPOSA PRIMARY KEY (FECHA_CAPTURA, HORA_CAPTURA, NOMBRE_ESPECIE, DNI_COLECCION),
	CONSTRAINT FK1_EJEMPLAR_MARIPOSA FOREIGN KEY (NOMBRE_ESPECIE) REFERENCES ESPECIE(NOMBRE),
	CONSTRAINT FK2_EJEMPLAR_MARIPOSA FOREIGN KEY (DNI_PERSONA) REFERENCES PERSONA(DNI),
	CONSTRAINT FK3_EJEMPLAR_MARIPOSA FOREIGN KEY (DNI_COLECCION) REFERENCES COLECCION(DNI_COLECCION),
	CONSTRAINT FK4_EJEMPLAR_MARIPOSA FOREIGN KEY (NOMBRE_ZONA) REFERENCES ZONA(NOMBRE)
);



--A
--1. El precio de un ejemplar debe ser superior a 0 euros.
ALTER TABLE EJEMPLAR_MARIPOSA ADD CONSTRAINT CHK_PRECIO_EJEMPLAR CHECK (PRECIO_EJEMPLAR>0);

--3. El atributo “Protegida” de la entidad Zona debe tomar como valores posibles “SI” o “NO”.
ALTER TABLE ZONA ADD CONSTRAINT CHK_PROTEGIDA CHECK (UPPER(PROTEGIDA) IN ('SI','NO'));

--4. La cantidad de los ejemplares de una colección debe estar comprendido entre 1 y 150.
ALTER TABLE COLECCION ADD CONSTRAINT CHK_N_EJEMPLARES CHECK (N_EJEMPLARES BETWEEN 1 AND 150);

--B
--1. Incluir un atributo para almacenar los apellidos de una persona.
ALTER TABLE PERSONA ADD APELLIDOS VARCHAR2(20);

--2. Incluir una restricción para controlar la extensión de una zona está entre 100m y 1500m
ALTER TABLE ZONA ADD CONSTRAINT CHK_EXTENSION CHECK (EXTENSION BETWEEN 100 AND 1500);

--3. Borra la restricción que obligaba a que los ejemplares tienen que tener un precio mayor que 0
ALTER TABLE EJEMPLAR_MARIPOSA DROP CONSTRAINT CHK_PRECIO_EJEMPLAR;

--4. El atributo fecha_captura de la tabla Ejemplar_mariposa tomará el valor por defecto la fecha actual.
ALTER TABLE EJEMPLAR_MARIPOSA MODIFY FECHA_CAPTURA DATE DEFAULT SYSDATE;







