CREATE TABLE CLIENTE
(
	DNI VARCHAR2(9),
	Nombre VARCHAR2(50),
	Apellidos VARCHAR2(50),
	Fecha_nacimiento DATE,
	Direccion VARCHAR2(50),
	CONSTRAINT PK_CLIENTE PRIMARY KEY (DNI) 
	
);

CREATE TABLE CATEGORIA 
(
	Nombre VARCHAR2(50),
	CONSTRAINT PK_CATEGORIA PRIMARY KEY (Nombre)
);

CREATE TABLE PRODUCTO
(
	Nombre VARCHAR2(50),
	precio NUMBER(5,2),
	cantidad NUMBER(10),
	Nombre_Categoria VARCHAR2(50) NOT NULL,
	CONSTRAINT PK_PRODUCTO PRIMARY KEY (Nombre),
	CONSTRAINT FK1_PRODUCTO FOREIGN KEY (Nombre_Categoria) REFERENCES CATEGORIA(Nombre) 
);

CREATE TABLE COMPRA
(
	DNI VARCHAR2(9),
	Nombre VARCHAR2(50),
	Fecha DATE,
	CONSTRAINT PK_COMPRA PRIMARY KEY (DNI, Nombre, Fecha),
	CONSTRAINT FK1_COMPRA FOREIGN KEY (DNI) REFERENCES CLIENTE(DNI),
	CONSTRAINT FK2_COMPRA FOREIGN KEY (Nombre) REFERENCES PRODUCTO(Nombre)
);






