INSERT INTO MUSEO (CODIGO, NOMBRE, PROVINCIA, DIRECCION)
VALUES ('1','MOMA','NEW YORK','LALA');

INSERT INTO MUSEO
VALUES ('2','MOMA','NEW YORK','LALA');

SELECT * FROM MUSEO
WHERE PROVINCIA LIKE 'NEW%';

UPDATE MUSEO SET NOMBRE='LOUVRE' WHERE CODIGO=2;

--DELETE FROM MUSEO
--WHERE PROVINCIA LIKE 'NEW%';