CREATE TABLE CABALLOS
(
	COD_CABALLO VARCHAR2(4),
	NOMBRE VARCHAR2(20) NOT NULL,
	PESO NUMBER(3),
	FECHA_NACIMIENTO DATE,
	PROPIETARIO VARCHAR2(25),
	NACIONALIDAD VARCHAR2(20),
	
	CONSTRAINT PK_CABALLOS PRIMARY KEY (COD_CABALLO),
	CONSTRAINT CHK_PESO CHECK (PESO>=240 AND PESO<=300),
	CONSTRAINT CHK_NACIONALIDAD CHECK (UPPER(NACIONALIDAD)=NACIONALIDAD),
	CONSTRAINT CHK_FECHA_NACIMIENTO CHECK (EXTRACT(YEAR FROM FECHA_NACIMIENTO)>2000)
);

CREATE TABLE CARRERAS
(
	COD_CARRERA VARCHAR2(4),
	FECHA_Y_HORA DATE,
	IMPORTE_PREMIO NUMBER(6),
	APUESTA_LIMITE NUMBER(5,2),
	
	CONSTRAINT PK_CARRERAS PRIMARY KEY (COD_CARRERA),
	CONSTRAINT CHK_APUESTA_LIMITE CHECK (APUESTA_LIMITE<20000),
	CONSTRAINT CHK_FECHA_Y_HORA CHECK (TO_CHAR(FECHA_Y_HORA, 'HH24:MI')>='09:00' AND TO_CHAR(FECHA_Y_HORA, 'HH24:MI')<='14:30')
);

CREATE TABLE PARTICIPANTES
(
	COD_CABALLO VARCHAR2(4),
	COD_CARRERA VARCHAR2(4),
	DORSAL NUMBER(2) NOT NULL,
	JOCKEY VARCHAR2(10) NOT NULL,
	POSICION_FINAL NUMBER(2),
	
	CONSTRAINT PK_PARTICIPANTES PRIMARY KEY (COD_CABALLO, COD_CARRERA),
	CONSTRAINT FK1_PARTICIPANTES FOREIGN KEY (COD_CABALLO) REFERENCES CABALLOS(COD_CABALLO),
	CONSTRAINT FK2_PARTICIPANTES FOREIGN KEY (COD_CARRERA) REFERENCES CARRERAS(COD_CARRERA),
	CONSTRAINT CHK_POSICION_FINAL CHECK (POSICION_FINAL > 0)
);

CREATE TABLE CLIENTES
(
	DNI VARCHAR2(10),
	NOMBRE VARCHAR2(20),
	NACIONALIDAD VARCHAR2(20),
	
	CONSTRAINT PK_CLIENTES PRIMARY KEY (DNI),
	CONSTRAINT CHK_DNI CHECK (REGEXP_LIKE(DNI, '^[0-9]{8}[A-Z]{1}')),
	CONSTRAINT CHK1_NACIONALIDAD CHECK (UPPER(NACIONALIDAD)=NACIONALIDAD)
);

CREATE TABLE APUESTAS
(
	DNI_CLIENTE VARCHAR(10),
	COD_CABALLO VARCHAR2(4),
	COD_CARRERA VARCHAR2(4),
	IMPORTE NUMBER(6) NOT NULL, --DEFAULT 300,
	TANTOPORUNO NUMBER(4,2),
	
	CONSTRAINT PK_APUESTAS PRIMARY KEY (DNI_CLIENTE, COD_CABALLO, COD_CARRERA),
	CONSTRAINT FK1_APUESTAS FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTES(DNI) ON DELETE CASCADE,
	CONSTRAINT FK2_APUESTAS FOREIGN KEY (COD_CABALLO) REFERENCES CABALLOS(COD_CABALLO) ON DELETE CASCADE,
	CONSTRAINT FK3_APUESTAS FOREIGN KEY (COD_CARRERA) REFERENCES CARRERAS(COD_CARRERA) ON DELETE CASCADE,
	CONSTRAINT CHK_TANTOPORUNO CHECK (TANTOPORUNO>1)
);


--2. Inserta el registro o registros necesarios para guardar la siguiente información:      
--El cliente escocés realiza una apuesta al caballo más pesado de la primera carrera que se corra en el verano de 2009 por un importe 
--de 2000 euros. En ese momento ese caballo en esa carrera se paga 30 a 1. Si es necesario algún dato invéntatelo, 
--pero sólo los datos que sean estrictamente necesaria.

INSERT INTO CLIENTES(DNI,NACIONALIDAD) VALUES ('12345678J','ESCOCES');
INSERT INTO CABALLOS(COD_CABALLO,NOMBRE,PESO) VALUES ('12D','ROCINANTE',300);
INSERT INTO CARRERAS(COD_CARRERA,FECHA_Y_HORA) VALUES ('123Z',TO_DATE('01/07/2009 09:30','DD/MM/YYYY HH24:MI'));
INSERT INTO APUESTAS VALUES ('12345678J','12D','123Z',2000,30);


---3. Inscribe a 2 caballos  en la carrera cuyo código es C6. La carrera aún no se ha celebrado. Invéntate los jockeys y 
--los dorsales y los caballos.

INSERT INTO CABALLOS VALUES ('00','PLATERO',250,TO_DATE('20/02/2004','DD/MM/YY'),NULL,'ESPANYOL');
INSERT INTO CABALLOS VALUES ('AA','ARABE',240,TO_DATE('15/05/2003','DD/MM/YY'),NULL,'MARROQUI');
INSERT INTO CARRERAS VALUES ('C6',TO_DATE('08/06/2023 14:30','DD/MM/YYYY HH24:MI'),2000,NULL);
INSERT INTO PARTICIPANTES VALUES ('00','C6',55,'Andres',NULL);
INSERT INTO PARTICIPANTES VALUES ('AA','C6',36,'Michael',NULL);

       
--4. Inserta dos carreras con los datos que creas necesario.
INSERT INTO CARRERAS VALUES ('C8',TO_DATE('15/08/2020 14:30','DD/MM/YYYY HH24:MI'),NULL,NULL);
INSERT INTO CARRERAS VALUES ('B7',TO_DATE('08/06/2021 14:30','DD/MM/YYYY HH24:MI'),NULL,NULL);

--5. Quita el campo propietario de la tabla caballos
ALTER TABLE CABALLOS DROP COLUMN PROPIETARIO;

--6. Añadir las siguientes restricciones a las tablas:
--• En la Tabla Participaciones los nombres de los jockeys tienen siempre las iniciales en mayúsculas.
--• La temporada de carreras transcurre del 10 de Marzo al 10 de Noviembre.
--• La nacionalidad de los caballos sólo puede ser Española, Británica o Árabe.
--Si los datos que has introducidos no cumplen las restricciones haz los cambios necesarios para ellos.

UPDATE CABALLOS SET NACIONALIDAD='ARABE' WHERE NOMBRE='ARABE';
UPDATE CABALLOS SET NACIONALIDAD='ESPAÑOL' WHERE NOMBRE='PLATERO';

ALTER TABLE PARTICIPANTES ADD CONSTRAINT CHK_JOCKEYS CHECK (INITCAP(JOCKEY)=JOCKEY);
ALTER TABLE CARRERAS ADD CONSTRAINT CHK_FECHAS CHECK ((TO_CHAR(FECHA_Y_HORA,'DD/MM')>='10/03') OR (TO_CHAR(FECHA_Y_HORA,'DD/MM')<='10/11'));
ALTER TABLE CABALLOS ADD CONSTRAINT CHK2_NACIONALIDAD CHECK (NACIONALIDAD IN ('ESPAÑOL','ARABE','BRITANICA'));


DELETE FROM CARRERAS WHERE COD_CARRERA NOT IN (SELECT COD_CARRERA FROM PARTICIPANTES);

--7.Añade un campo llamado código en el campo clientes, que no permita valores nulos ni repetidos
CREATE SEQUENCE SQ_CL
START WITH 1
INCREMENT BY 1;
SELECT SQ_CL.nextval FROM DUAL;
ALTER TABLE CLIENTES ADD CODIGO VARCHAR2(4);
UPDATE CLIENTES SET CODIGO=SQ_CL.nextval;
ALTER TABLE CLIENTES MODIFY CODIGO VARCHAR2(4) UNIQUE;


--8.Nos hemos equivocado y el código C6 de la carrera en realidad es C66.
INSERT INTO CARRERAS(COD_CARRERA) VALUES ('C66');
UPDATE PARTICIPANTES SET COD_CARRERA='C66' WHERE COD_CARRERA LIKE'C6';
DELETE FROM CARRERAS WHERE COD_CARRERA LIKE 'C6';
SELECT * FROM CARRERAS;


--9.Añade un campo llamado premio a la tabla apuestas.
ALTER TABLE APUESTAS ADD PREMIO NUMBER(6);

--10.Borra todas las tablas y datos con el número menor de instrucciones posibles.
DROP TABLE APUESTAS CASCADE CONSTRAINT;
DROP TABLE CABALLOS CASCADE CONSTRAINT;
DROP TABLE CARRERAS CASCADE CONSTRAINT;
DROP TABLE CLIENTES CASCADE CONSTRAINT;
DROP TABLE PARTICIPANTES CASCADE CONSTRAINT;



--(EXTRACT (DAY FROM FECHAHORA))>28
--(EXTRACT (YEAR FROM FECHAHORA))>2022
--(EXTRACT (MONTH FROM FECHAHORA))>12

--TO_CHAR(FECHAHORA,'HH24:MI')>='9:00'

--INSERT INTO COMPRA VALUES (1, TO_DATE('12/05/1999','DD/MM/YYYY'))

