CREATE TABLE DEPARTAMENTOS
(
	CODIGO NUMBER(20),
	DESCRIPCION VARCHAR2(100),
	
	CONSTRAINT PK_DEPARTAMENTOS PRIMARY KEY (CODIGO)
);

CREATE SEQUENCE SQ_COD_DEPARTAMENTOS
START WITH 1
INCREMENT BY 1;

SELECT SQ_COD_DEPARTAMENTOS.nextval FROM DUAL;

INSERT INTO DEPARTAMENTOS(CODIGO,DESCRIPCION) VALUES (SQ_COD_DEPARTAMENTOS.currval,'Ventas');
INSERT INTO DEPARTAMENTOS VALUES (SQ_COD_DEPARTAMENTOS.nextval,'Direccion');
INSERT INTO DEPARTAMENTOS VALUES (SQ_COD_DEPARTAMENTOS.nextval,'Logistica');
INSERT INTO DEPARTAMENTOS VALUES (SQ_COD_DEPARTAMENTOS.nextval,'Tecnico');

SELECT * FROM DEPARTAMENTOS;
