CREATE TABLE FABRICANTES
(
	COD_FABRICANTE NUMBER(3),
	NOMBRE VARCHAR2(15),
	PAIS VARCHAR2(15),
	
	CONSTRAINT PK_FABRICANTES PRIMARY KEY (COD_FABRICANTE),
	CONSTRAINT CHK1_FABRICANTES CHECK (UPPER(NOMBRE)=NOMBRE),
	CONSTRAINT CHK2_FABRICANTES CHECK (UPPER(PAIS)=PAIS)
);

CREATE TABLE ARTICULOS
(
	ARTICULO VARCHAR2(20),
	COD_FABRICANTE NUMBER(3),
	PESO NUMBER(3),
	CATEGORIA VARCHAR2(10),
	PRECIO_VENTA NUMBER(4,2),
	PRECIO_COSTO NUMBER(4,2),
	EXISTENCIAS NUMBER(5),
	
	CONSTRAINT PK_ARTICULOS PRIMARY KEY (ARTICULO,COD_FABRICANTE,PESO,CATEGORIA),
	CONSTRAINT FK1_ARTICULOS FOREIGN KEY (COD_FABRICANTE) REFERENCES FABRICANTES(COD_FABRICANTE),
	CONSTRAINT CHK1_ARTICULOS CHECK (CATEGORIA IN ('PRIMERA','SEGUNDA','TERCERA')),
	CONSTRAINT CHK2_ARTICULOS CHECK (PRECIO_VENTA > 0 AND PRECIO_COSTO > 0 AND EXISTENCIAS > 0)
	
);

CREATE TABLE TIENDAS
(
	NIF VARCHAR(10),
	NOMBRE VARCHAR2(20),
	DIRECCION VARCHAR2(20),
	POBLACION VARCHAR2(20),
	PROVINCIA VARCHAR2(20),
	CODPOSTAL NUMBER(5), 
	
	CONSTRAINT PK_TIENDAS PRIMARY KEY (NIF),
	CONSTRAINT CHK_TIENDAS CHECK (UPPER(PROVINCIA)=PROVINCIA)
);

CREATE TABLE PEDIDOS
(
	NIF VARCHAR2(10),
	ARTICULO VARCHAR2(20),
	COD_FABRICANTE NUMBER(3),
	PESO NUMBER(3),
	CATEGORIA VARCHAR2(10),
	FECHA_PEDIDO DATE,
	UNIDADES_PEDIDAS NUMBER(4),
	
	CONSTRAINT PK_PEDIDOS PRIMARY KEY (NIF,ARTICULO, COD_FABRICANTE, PESO, CATEGORIA,FECHA_PEDIDO),
	CONSTRAINT FK1_PEDIDOS FOREIGN KEY (COD_FABRICANTE) REFERENCES FABRICANTES(COD_FABRICANTE),
	CONSTRAINT FK2_PEDIDOS FOREIGN KEY (ARTICULO,COD_FABRICANTE,PESO,CATEGORIA) REFERENCES ARTICULOS(ARTICULO,COD_FABRICANTE,PESO,CATEGORIA) ON DELETE CASCADE,
	CONSTRAINT FK3_PEDIDOS FOREIGN KEY (NIF) REFERENCES TIENDAS(NIF),
	CONSTRAINT CHK1_PEDIDOS CHECK (UNIDADES_PEDIDAS > 0)
	
);

CREATE TABLE VENTAS
(
	NIF VARCHAR2(10),
	ARTICULO VARCHAR2(20),
	COD_FABRICANTE NUMBER(3),
	PESO NUMBER(3),
	CATEGORIA VARCHAR2(10),
	FECHA_VENTA DATE DEFAULT SYSDATE, 
	UNIDADES_VENDIDAS NUMBER(4),
	
	CONSTRAINT PK_VENTAS PRIMARY KEY (NIF,ARTICULO,COD_FABRICANTE,PESO,CATEGORIA,FECHA_VENTA),
	CONSTRAINT FK1_VENTAS FOREIGN KEY (COD_FABRICANTE) REFERENCES FABRICANTES(COD_FABRICANTE),
	CONSTRAINT FK2_VENTAS FOREIGN KEY (ARTICULO,COD_FABRICANTE,PESO,CATEGORIA) REFERENCES ARTICULOS(ARTICULO,COD_FABRICANTE,PESO,CATEGORIA) ON DELETE CASCADE,
	CONSTRAINT FK3_VENTAS FOREIGN KEY (NIF) REFERENCES TIENDAS(NIF),
	CONSTRAINT CHK1_VENTAS CHECK (UNIDADES_VENDIDAS > 0)
	
	
);

--1. Modificar las columnas de las tablas pedidos y ventas para que las
--unidades_vendidas y las unidades_pedidas puedan almacenar cantidades numéricas
--de 6 dígitos.
ALTER TABLE PEDIDOS MODIFY UNIDADES_PEDIDAS NUMBER(6);
ALTER TABLE VENTAS MODIFY UNIDADES_VENDIDAS NUMBER(6);

--2. Añadir a las tablas pedidos y ventas una nueva columna para que almacenen el PVP
--del artículo
ALTER TABLE PEDIDOS ADD PVP NUMBER(6,2);
ALTER TABLE VENTAS ADD PVP NUMBER(6,2);

--3. Borra la columna pais de la tabla fabricante. NO ME VA
ALTER TABLE FABRICANTES DROP COLUMN PAIS;

--4. Añade una restricción que indique que las unidades vendidas son como mínimo 100
ALTER TABLE VENTAS ADD CONSTRAINT CHK2_VENTAS CHECK (UNIDADES_VENDIDAS >= 100);

--5. Borra la restricción anterior
ALTER TABLE VENTAS DROP CONSTRAINT CHK2_VENTAS;

--6. Borra todas las tablas creadas.
DROP TABLE VENTAS CASCADE CONSTRAINT;
DROP TABLE PEDIDOS CASCADE CONSTRAINT;
DROP TABLE TIENDAS CASCADE CONSTRAINT;
DROP TABLE ARTICULOS CASCADE CONSTRAINT;
DROP TABLE FABRICANTES CASCADE CONSTRAINT;

















